spring:
  application:
    name: enotes-api-service
  profiles:
    active: test
    
---
# dev Config
spring:
  config:
    activate:
      on-profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_dev
    username: root
    password: abhi123
  jpa:
    hibernate:
      ddl-auto: update
   
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect 
    
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB  
      


#email Configurations
  mail:
    host: smtp.gmail.com
    port: 587
    username: abhisheknarkharkhede083@gmail.com
    password: vgzg pnyr gneo vzjo
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true  
        
            
file:
  upload:
    path: notes/ 
    


---
# test Config
spring:
  config:
    activate:
      on-profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_test
    username: root
    password: abhi123
  jpa:
    hibernate:
      ddl-auto: update
   
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect 
    
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB  
      


#email Configurations
  mail:
    host: smtp.gmail.com
    port: 587
    username: abhisheknarkharkhede083@gmail.com
    password: vgzg pnyr gneo vzjo
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true  
        
            
file:
  upload:
    path: notes/ 


---
# uat Config
spring:
  config:
    activate:
      on-profiles: uat
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_uat
    username: root
    password: abhi123
  jpa:
    hibernate:
      ddl-auto: update
   
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect 
    
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB  
      


#email Configurations
  mail:
    host: smtp.gmail.com
    port: 587
    username: abhisheknarkharkhede083@gmail.com
    password: vgzg pnyr gneo vzjo
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true  
        
            
file:
  upload:
    path: notes/ 
    

---
# prod Config
spring:
  config:
    activate:
      on-profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/enotes_prod
    username: root
    password: abhi123
  jpa:
    hibernate:
      ddl-auto: update
   
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect 
    
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB  
      


#email Configurations
  mail:
    host: smtp.gmail.com
    port: 587
    username: abhisheknarkharkhede083@gmail.com
    password: vgzg pnyr gneo vzjo
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true  
        
            
file:
  upload:
    path: notes/ 
    
   